### ISSUE TITLE
Error in Rate Parser Example

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/RateParser#10]
@christophertull do you know why I'd be getting the following error?  Rate Parser is correctly installing though blows up when I try to run the example: 

> library(RateParser)
> owrs_file <- read_owrs_file("examples/smc-2016-03-01.owrs")
Error in file(con, "rb") : cannot open the connection
In addition: Warning message:
In file(con, "rb") :
  cannot open file 'examples/smc-2016-03-01.owrs': No such file or directory

**Comment by christophertull** [comment]
My first guess would be wrong working directory in R?

**Comment by christophertull** [comment]
Updated README to reflect how to get the OWRS file.
